# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.lab_main = QtWidgets.QLabel(self.centralwidget)
        self.lab_main.setGeometry(QtCore.QRect(220, 90, 330, 420))
        self.lab_main.setStyleSheet("QLabel {\n"
"    background-color: rgb(255, 255, 255);    \n"
"    border-radius: 15px;\n"
"}")
        self.lab_main.setText("")
        self.lab_main.setObjectName("lab_main")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(430, 95, 101, 51))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setStyleSheet("QFrame {\n"
"    border: nona;\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    padding-bottom: 5px; \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top: 5px; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_hide = QtWidgets.QPushButton(self.frame)
        self.btn_hide.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_hide.setIcon(icon)
        self.btn_hide.setIconSize(QtCore.QSize(20, 20))
        self.btn_hide.setObjectName("btn_hide")
        self.horizontalLayout.addWidget(self.btn_hide)
        self.btn_cancel = QtWidgets.QPushButton(self.frame)
        self.btn_cancel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon1)
        self.btn_cancel.setIconSize(QtCore.QSize(20, 20))
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.lab_title = QtWidgets.QLabel(self.centralwidget)
        self.lab_title.setGeometry(QtCore.QRect(270, 150, 230, 40))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lab_title.setFont(font)
        self.lab_title.setObjectName("lab_title")
        self.led_username = QtWidgets.QLineEdit(self.centralwidget)
        self.led_username.setGeometry(QtCore.QRect(270, 230, 230, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.led_username.setFont(font)
        self.led_username.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(0, 0, 0)\n"
"}")
        self.led_username.setText("")
        self.led_username.setClearButtonEnabled(True)
        self.led_username.setObjectName("led_username")
        self.led_password = QtWidgets.QLineEdit(self.centralwidget)
        self.led_password.setGeometry(QtCore.QRect(270, 310, 230, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.led_password.setFont(font)
        self.led_password.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(0, 0, 0)\n"
"}")
        self.led_password.setText("")
        self.led_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.led_password.setClearButtonEnabled(True)
        self.led_password.setObjectName("led_password")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(270, 400, 230, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("QPushButton {\n"
"    background-color: rgb(95, 185, 147);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px ;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 113, 110);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-top: 5px; \n"
"    padding-left: 5px; \n"
"}\n"
"\n"
"\n"
"")
        self.btn_login.setObjectName("btn_login")
        self.ckb_remember = QtWidgets.QCheckBox(self.centralwidget)
        self.ckb_remember.setGeometry(QtCore.QRect(270, 355, 79, 20))
        self.ckb_remember.setChecked(False)
        self.ckb_remember.setObjectName("ckb_remember")
        self.fra_qq_wx = QtWidgets.QFrame(self.centralwidget)
        self.fra_qq_wx.setGeometry(QtCore.QRect(300, 460, 170, 45))
        self.fra_qq_wx.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fra_qq_wx.setStyleSheet("QFrame {\n"
"    border: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top: 5px; \n"
"    padding-left: 5px; \n"
"}")
        self.fra_qq_wx.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fra_qq_wx.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fra_qq_wx.setObjectName("fra_qq_wx")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fra_qq_wx)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_qq = QtWidgets.QPushButton(self.fra_qq_wx)
        self.btn_qq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_qq.setStyleSheet("")
        self.btn_qq.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/qq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_qq.setIcon(icon2)
        self.btn_qq.setIconSize(QtCore.QSize(25, 25))
        self.btn_qq.setObjectName("btn_qq")
        self.horizontalLayout_2.addWidget(self.btn_qq)
        self.btn_wx = QtWidgets.QPushButton(self.fra_qq_wx)
        self.btn_wx.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_wx.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/wx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wx.setIcon(icon3)
        self.btn_wx.setIconSize(QtCore.QSize(25, 25))
        self.btn_wx.setObjectName("btn_wx")
        self.horizontalLayout_2.addWidget(self.btn_wx)
        self.btn_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_set.setGeometry(QtCore.QRect(380, 95, 51, 51))
        self.btn_set.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_set.setStyleSheet("QPushButton {\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top: 5px; \n"
"    padding-left: 5px; \n"
"}")
        self.btn_set.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("static/set.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_set.setIcon(icon4)
        self.btn_set.setIconSize(QtCore.QSize(25, 25))
        self.btn_set.setObjectName("btn_set")
        self.lab_main.raise_()
        self.frame.raise_()
        self.lab_title.raise_()
        self.led_username.raise_()
        self.led_password.raise_()
        self.btn_login.raise_()
        self.fra_qq_wx.raise_()
        self.btn_set.raise_()
        self.ckb_remember.raise_()
        login.setCentralWidget(self.centralwidget)

        self.retranslateUi(login)
        self.btn_cancel.clicked.connect(login.close) # type: ignore
        self.btn_hide.clicked.connect(login.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "MainWindow"))
        self.lab_title.setText(_translate("login", "<html><head/><body><p align=\"center\">欢迎登陆</p></body></html>"))
        self.led_username.setPlaceholderText(_translate("login", "账号:"))
        self.led_password.setPlaceholderText(_translate("login", "密码:"))
        self.btn_login.setText(_translate("login", "登录"))
        self.ckb_remember.setText(_translate("login", "记住"))
